### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by StuLiu** [ggsDing/LANet#2]
Hi! Thanks for your submission.
I cloned the repository yesterday. Howerver, there were not any python files in the 'utils' module. Could you please upload the missing code, and draft a simple guide.

**Comment by DingLei14** [comment]
Hi.
Sorry I missed these files. I just updated. I will write a guide later

**Comment by StuLiu** [comment]
@ggsDing Thank you very much!

**Comment by DingLei14** [comment]
> 

Hi, a simple guide is provided now. Also the codes have been optimized.
You can also check our latest work at: https://github.com/ggsDing/WiCoNet
